Fix improper type cast in Asset.issue()
Regression introduced in bbfefab39418ff3106c56265fd66cfc186d0b51e.
Casting amount to int leads to effectively zeroing amounts < 1 (e.g.
0.01 -> 0), causing a node error:
grapheneapi.exceptions.RPCError: asset_to_issue.amount.value > 0: